- Services:
  - Top:
      - TrueNAS:
          id: TrueNAS
          icon: si-truenas
          href: http://your.server.ip
          siteMonitor: http://your.server.ip
          statusStyle: dot
          widgets:
            - type: truenas
              fields: ["uptime", "alerts"]
              url: http://your.server.ip
              key: # not required if using username / password
              enablePools: true # optional, defaults to false
              nasType: scale # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core
            - type: prometheusmetric
              url: http://your.server.ip
              refreshInterval: 5000
              metrics:
              - label: CPU
                query:
                format:
                  type: percent
              - label: CPU Temp (°F)
                query:
              - label: UPS Load
                query:
                format:
                  type: percent
              - label: UPS Charge
                query:
                format:
                  type: percent

  - Lower:
      - Immich:
          icon: si-immich
          href: http://your.server.ip:port
          siteMonitor: http://your.server.ip:port
          statusStyle: dot
          widgets:
            - type: immich
              fields: ["photos", "videos", "storage"]
              url: http://your.server.ip:port
              key:
              version: 2
            - type: prometheusmetric
              url: http://your.server.ip:port
              refreshInterval: 5000
              metrics:
              - label: CPU
                query:
                format:
                  type: percent
              - label: RAM (GB)
                query:
      - TubeArchivist:
          icon: https://raw.githubusercontent.com/owennewo-dev/Homepage-config/365cea01addc43a46337ba1de6571808bb3f0a65/Icons/tubearchivist.svg
          href: http://your.server.ip:port
          siteMonitor: http://your.server.ip:port
          statusStyle: dot
          widgets:
            - type: tubearchivist
              fields: ["downloads", "videos", "channels"]
              url: http://your.server.ip:port
              key:
            - type: prometheusmetric
              url: http://your.server.ip:port
              refreshInterval: 5000
              metrics:
              - label: CPU
                query:
                format:
                  type: percent
              - label: RAM
                query:
      - Grafana:
          icon: si-grafana
          href: http://your.server.ip:port
          siteMonitor: http://your.server.ip:port
          statusStyle: dot
          widgets:
            - type: grafana
              url: http://your.server.ip:port
              username:
              password:
            - type: prometheusmetric
              url: http://your.server.ip:port
              refreshInterval: 5000
              metrics:
              - label: CPU
                query:
                format:
                  type: percent
              - label: RAM (GB)
                query:
      - Prometheus:
          icon: si-prometheus
          href: http://your.server.ip:port
          siteMonitor: http://your.server.ip:port
          statusStyle: dot
          widgets:
            - type: prometheus
              fields: ["targets_up", "targets_down"]
              url: http://your.server.ip:port
            - type: prometheusmetric
              url: http://your.server.ip:port
              refreshInterval: 5000
              metrics:
              - label: CPU
                query:
                format:
                  type: percent
              - label: RAM (GB)
                query:
      - NetAlertX:
          id: NetAlertX
          icon: https://raw.githubusercontent.com/owennewo-dev/Homepage-config/38292941b3ab1de5caa0d3f6740459d6ec4624d3/Icons/netalertx.svg
          href: http://your.server.ip:port
          siteMonitor: http://your.server.ip:port
          statusStyle: dot
          widgets:
            - type: netalertx
              fields: ["connected", "new_devices", "down_alerts"]
              url: http://your.server.ip:port
            - type: prometheusmetric
              url: http://your.server.ip:port
              refreshInterval: 5000
              metrics:
              - label: CPU
                query:
                format:
                  type: percent
              - label: RAM (GB)
                query:
      - Tailscale:
          icon: si-tailscale
          href: https://login.tailscale.com/admin/machines
          widgets:
            - type: tailscale
              fields: ["address", "last_seen"]
              deviceid:
              key:
            - type: tailscale
              fields: ["address", "last_seen"]
              deviceid:
              key:
  - Lowest:
      - Nextcloud:
          icon: si-nextcloud
          href: http://your.server.ip:port
          siteMonitor: http://your.server.ip:port
          statusStyle: dot
          widget:
            type: prometheusmetric
            url: http://your.server.ip:port
            refreshInterval: 5000
            metrics:
            - label: CPU
              query:
              format:
                type: percent
            - label: RAM (GB)
              query:
      - Graphite Exporter:
          icon: si-prometheus
          href: http://your.server.ip:port
          siteMonitor: http://your.server.ip:port
          statusStyle: dot
          widget:
            type: prometheusmetric
            url: http://your.server.ip:port
            refreshInterval: 5000
            metrics:
            - label: CPU
              query:
              format:
                type: percent
            - label: RAM (GB)
              query:
      - Emby:
          icon: si-emby
          href: http://your.server.ip:port
          siteMonitor: http://your.server.ip:port
          statusStyle: dot
          widget:
            type: prometheusmetric
            url: http://your.server.ip:port
            refreshInterval: 5000
            metrics:
            - label: CPU
              query:
              format:
                type: percent
            - label: RAM (GB)
              query:

- Blocks:
  - MailCalendar:
      - Calendar:
          widget:
            type: calendar
            firstDayInWeek: sunday # optional - defaults to monday
            view: monthly # optional - possible values monthly, agenda
            maxEvents: 50 # optional - defaults to 10
            showTime: true # optional - show time for event happening today - defaults to false
            timezone: America/Denver # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or dif>        - Gmail:
      - Links:
          - Gmail:
              icon: si-gmail
              href: https://mail.google.com/mail/u/0/
          - Google Calendar:
              icon: si-googlecalendar
              href: https://calendar.google.com/calendar/u/0/r
          - Github:
              icon: si-github
              href: https://github.com/

  - Planes:
      - ADS-B Exchange:
          icon: https://raw.githubusercontent.com/owennewo-dev/Homepage-config/644f39bd5f1bf67e18981f6d1ec026fc5c8215f0/Icons/flightradar24.svg
          widget:
            type: iframe
            name: ADS-B Exchange
            src: https://globe.adsbexchange.com/
            classes: h-72 # optional, use tailwind height classes, see https://tailwindcss.com/docs/height
            referrerPolicy: same-origin # optional, no default
            allowPolicy: fullscreen # optional, no default
            allowFullscreen: false # optional, default: true
            loadingStrategy: eager # optional, default: eager
            allowScrolling: no # optional, default: yes
      - ATC:
         - Tower/Approach:
             icon: https://raw.githubusercontent.com/owennewo-dev/Homepage-config/644f39bd5f1bf67e18981f6d1ec026fc5c8215f0/Icons/flightradar24.svg
             href: https://www.liveatc.net
         - Delivery/Ground:
             icon: https://raw.githubusercontent.com/owennewo-dev/Homepage-config/644f39bd5f1bf67e18981f6d1ec026fc5c8215f0/Icons/flightradar24.svg
             href: https://www.liveatc.net