color: gray
theme: dark

background:
  image: https://i.imgur.com/s4Fqur6.gif
cardBlur: "" # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur

hideVersion: true

useEqualHeights: true

headerStyle: boxedWidgets

iconStyle: theme

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Services:
    style: column
    columns: 1
    header: false
    Top:
      style: row
      columns: 1
      header: false
    Lower:
      style: row
      columns: 2
      header: false
    Lowest:
      style: row
      columns: 3
      header: false
    Glances:
      style: row
      columns: 3
      header: false
  Blocks:
    style: column
    columns: 1
    header: false
    MailCalendar:
      style: row
      columns: 1
      header: false
      Links:
        style: row
        columns: 3
        header: false
    Planes:
      style: column
      columns: 1
      header: false
      ATC:
        style: row
        columns: 2
        header: false
  Bookmarks:
    iconsOnly: true
    style: row
    columns: 10
    disableCollapse: true
    header: false